from functions import *

init()

table(mgold, c("wrench"), ingots(3), c("cogwheel"))
table(maa, c("andesite_alloy"), ingots(1), "tconstruct:ingot_cast")
table(maa, "econstruct:andesite_alloy_nugget", nuggets(1), "tconstruct:nugget_cast", time=5)
basin(maa, "econstruct:andesite_alloy_block", ingots(9), cooling_time=140)
basin(ma, "minecraft:andesite", ingots(9), cooling_time=120)

melt(c("wrench"), mgold, ingots(3))

melt(c("filter"), miron, nuggets(2))
melt(c("mechanical_saw"), miron, ingots(4))
melt(c("mechanical_plough"), miron, ingots(3), byproducts=[maa], amounts=[ingots(4)])
melt(c("mechanical_harvester"), miron, ingots(2), byproducts=[maa], amounts=[ingots(5)])
melt(c("minecart_coupling"), miron, ingots(1), byproducts=[maa], amounts=[ingots(2)])
melt(c("rope_pulley"), miron, ingots(1), byproducts=[maa], amounts=[ingots(1)])
melt(c("propeller"), miron, ingots(4), byproducts=[maa], amounts=[ingots(1)])
melt(c("whisk"), miron, ingots(5), byproducts=[maa], amounts=[ingots(2)])
melt(c("empty_blaze_burner"), miron, ingots(4))
melt(c("blaze_burner"), miron, ingots(4))
melt(c("fluid_valve"), miron, ingots(1))
melt(c("electron_tube"), miron, ingots(1))
melt(c("redstone_contact"), miron, 45)
melt(c("item_vault"), miron, ingots(2))
melt(c("schematicannon"), miron, ingots(18), time=45 * 25)
melt(c("metal_bracket"), miron, nuggets(10))

melt(c("attribute_filter"), mbrass, nuggets(2))
melt(c("smart_chute"), mbrass, ingots(1))
melt(c("peculiar_bell"), mbrass, ingots(10), time=45 * 20)
melt(c("flywheel"), mbrass, ingots(8), time=45 * 15)
melt(c("haunted_bell"), mbrass, ingots(10), time=45 * 20)
melt(c("deployer"), mbrass, ingots(4))
melt(c("mechanical_arm"), mbrass, ingots(4))
melt(c("smart_fluid_pipe"), mbrass, ingots(1))
melt(c("pulse_repeater"), mbrass, ingots(1))
melt(c("train_door"), mbrass, ingots(1))
melt(c("train_trapdoor"), mbrass, ingots(1))
melt(c("pulse_extender"), mbrass, ingots(1))
melt(c("placard"), mbrass, ingots(1))
melt(c("brass_tunnel"), mbrass, ingots(1))
melt(c("brass_funnel"), mbrass, 45)

melt(c("bar_of_chocolate"), "create:chocolate", 250)
table(maa, c("bar_of_chocolate"), 250, "tconstruct:ingot_cast", time=20)
table(maa, c("chocolate_glazed_berries"), 250, "minecraft:sweet_berries", time=20, consume_cast=True)

melt("create:rose_quartz_lamp", mzinc, ingots(1))

melt("create:valve_handles", mcopper, ingots(3), byproducts=[maa], amounts=[ingots(1)], tag=True)
melt("create:steam_engine", mcopper, ingots(9), byproducts=[maa, mgold], amounts=[ingots(1), ingots(1)])
melt("create:steam_whistle", mcopper, ingots(1), byproducts=[mgold], amounts=[ingots(1)])
melt("create:display_link", mcopper, ingots(1))
melt("create:copper_casing", mcopper, ingots(1))
melt("create:spout", mcopper, ingots(1))
melt("create:portable_fluid_interface", mcopper, ingots(1))
melt("create:fluid_tank", mcopper, ingots(2))
melt("create:hose_pulley", mcopper, ingots(2))
melt("create:copper_backtank", mcopper, ingots(12), byproducts=[maa], amounts=[ingots(2)])
melt("create:item_drain", mcopper, ingots(1), byproducts=[miron], amounts=[nuggets(3)])
melt(c("copper_tiles"), mcopper, 45)
melt(c("copper_shingles"), mcopper, 45)

melt("minecraft:andesite", ma, 100)
melt("minecraft:andesite_slab", ma, 50)
melt("minecraft:andesite_stairs", ma, 100)
melt("minecraft:polished_andesite", ma, 100)
melt("minecraft:polished_andesite_slab", ma, 50)
melt("minecraft:andesite_stairs", ma, 100)
melt("minecraft:andesite_wall", ma, 100)
melt("create:stone_types/andesite", ma, 100, tag=True)

melt(c("brass_ladder"), mbrass, 45)
melt(c("copper_ladder"), mcopper, 45)

melt("create:display_board", maa, ingots(1))
melt("create:andesite_alloy", maa, ingots(1))
melt("create:depot", maa, ingots(2))
melt("create:cart_assembler", maa, ingots(2))
melt("create:mechanical_piston", maa, ingots(1))
melt("create:basin", maa, ingots(5))
melt("create:sticky_mechanical_piston", maa, ingots(1))
melt("create:andesite_alloy", maa, ingots(1))
melt("econstruct:andesite_alloy_block", maa, ingots(9), time=800)
melt("econstruct:andesite_alloy_nugget", maa, nuggets(1))
melt("create:mechanical_drill", maa, ingots(3), byproducts=[miron], amounts=[ingots(1)])
melt(c("sticker"), maa, ingots(2))
melt(c("nozzle"), maa, ingots(4))
melt(c("linear_chassis"), maa, ingots(1) * 2 / 3)
melt(c("secondary_linear_chassis"), maa, ingots(1) * 2 / 3)
melt(c("radial_chassis"), maa, ingots(1) * 2 / 3)
melt(c("andesite_tunnel"), maa, ingots(1))
melt(c("andesite_funnel"), maa, 45)
melt(c("white_sail"), maa, 45)

for x in crushed_ores_with_corresponding_molten_metals:
    melt(f"create:crushed_{x}_ore", f"tconstruct:molten_{x}", ingots(1))

alloy([ma, miron], [100, 10], maa, 90)
alloy([ma, mzinc], [100, 10], maa, 90)
